spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marcenaria
    username: crmuser
    password: crmpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "uma_chave_secreta_bem_grande_e_segura"
  expiration: 3600000 # 1 hora em milissegundos
