spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marcenaria
    username: crmuser
    password: crmpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
